### ISSUE TITLE
Documentation website errors

### ISSUE THREAD

**Issue by jpadfield** [bplmaps/panel-truck#1]
Hi, I just noticed that lots or JS files are failing to load for: https://geoservices.leventhalmap.org/cartinal/documentation/panel-truck.html - so the formatting of the page seems to be broken.

**Comment by garrettdashnelson** [comment]
Ah, we moved our Cartinal app to a subdomain and it looks like some of the URL rewrites aren't pointed there.

You can find the documentation at https://cartinal.leventhalmap.org/documentation/panel-truck.html — thanks for the catch!
